### ISSUE TITLE
dumpdata error on django==2.0.8

### ISSUE THREAD

**Issue by ofirule** [dmkoch/django-jsonfield#221]
python3.5
django==2.0.8

```
root@root:/backend# : python manage.py dumpdata

[.......................................................................... ]CommandError: Unable to serialize database: 'JSONField' object has no attribute '_get_val_from_obj'
```

**Comment by ofirule** [comment]
Used old version 1.0.1 , works on 2.0.2
